@host = http://localhost:8080

### Login
# @name login
post {{host}}/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "test1"
}

### create User
post {{host}}/api/user
token: bearer {{token}}
Content-Type: application/json

{
  "name": "test5",
  "lastName": "test5",
  "email": "test5@gmail.com",
  "password": "test5",
  "dni": "1125155434",
  "phones": [
    {
      "type": "CASA",
      "value": "577747"
    },
        {
      "type": "celular",
      "value": "0987476374"
    }
  ],
  "addresses": [
    {
      "type": "CASA",
      "value": "Ciudad alegria frente al reten"
    }
  ],
  "roles": [
    "1ec955d8-4e17-46ea-aeb9-9b8d3b1dbce3"
  ]
}

### get Users
@token = {{login.response.body.credential.token}}
###
get {{host}}/api/user
token: bearer {{token}}

### get User by Id
get {{host}}/api/user/549e92ff-f483-47ac-9d69-a4856389f150
token: bearer {{token}}

### update User
put {{host}}/api/user/549e92ff-f483-47ac-9d69-a4856389f150
token: bearer {{token}}
Content-Type: application/json

{
  "name": "Diegoooo",
  "lastName": "tinitana",
  "email": "test4@gmail.com",
  "dni": "1125154476",
  "isActive": true,
  "roles": [
    "05bee02e-4ad7-47ae-b776-ab621e04d42f"
  ]
}

### delete user
delete {{host}}/api/user/549e92ff-f483-47ac-9d69-a4856389f150
token: bearer {{token}}

###client
post {{host}}/api/client
token: bearer {{token}}
Content-Type: application/json

{
  "name": "test5",
  "lastName": "test5",
  "email": "test5@gmail.com",
  "dni": "1125155434",
  "phone": "0987174750",
  "address": "ciudad alegria"
}

### get clients
get {{host}}/api/client
token: bearer {{token}}

### get client
get {{host}}/api/client/375d5f04-7fd8-44c3-907c-589be4c59bc3
token: bearer {{token}}

### update client
put {{host}}/api/client/375d5f04-7fd8-44c3-907c-589be4c59bc3
token: bearer {{token}}
Content-Type: application/json

{
  "name": "test5",
  "lastName": "test5",
  "email": "test5@gmail.com",
  "dni": "1125155434",
  "phone": "0987174750",
  "address": "ciudad alegria Loja Ecuador"
}

### delete client
delete {{host}}/api/client/a25444d4-6f9e-4206-a120-0367a413d84b
token: bearer {{token}}

# items
### create
post {{host}}/api/item
token: bearer {{token}}
Content-Type: application/json

{
  "name": "Carne",
  "description": "es un carne",
  "code": "A001",
  "barCode": "A001",
  "hasIva": true,
  "purchasePrice": 20,
  "pvps": [
    {
      "id": 1,
      "value": 22,
      "percent": 10
    }
  ]
}

### get
get {{host}}/api/item
token: bearer {{token}}

### get by id
get {{host}}/api/item/d9a5dcf7-3d64-41ef-8efb-5beb8e4a9b4d
token: bearer {{token}}

### get by code or barcode
get {{host}}/api/item/code
    ?code=L001
token: bearer {{token}}

### update
put {{host}}/api/item/d9a5dcf7-3d64-41ef-8efb-5beb8e4a9b4d
token: bearer {{token}}
Content-Type: application/json

{
  "name": "telefono000000",
  "description": "es un telefono",
  "code": "001",
  "barCode": "b001",
  "hasIva": true,
  "purchasePrice": 20
}

### set item to categories
post {{host}}/api/item/categories?id=cc5a3491-dbfe-4064-86c3-03803610b3f9
token: bearer {{token}}
Content-Type: application/json

{
  "categories" : ["d7f88e48-3274-4af4-bb82-f0d69c4a27c4", "d8979afd-c822-4934-918c-cba52bad6270"]
}

# close items

# provider

### create
post {{host}}/api/provider
token: bearer {{token}}
Content-Type: application/json

{
  "name": "test5",
  "lastName": "test5",
  "email": "test5@gmail.com",
  "dni": "1125155434",
  "phones": [
    {
      "type": "CASA",
      "value": "072998488737"
    },
        {
      "type": "celular",
      "value": "0988437737"
    }
  ],
  "addresses": [
    {
      "type": "Sucursl 1",
      "value": "frente al mercado central"
    }
  ],
  "company": "Romar"
}

### get all
get {{host}}/api/provider
token: bearer {{token}}

### get by id
{{host}}/api/provider/81baed53-e44e-406f-b192-8aa61fb02c2c
token: bearer {{token}}

### update
put {{host}}/api/provider/81baed53-e44e-406f-b192-8aa61fb02c2c
token: bearer {{token}}
Content-Type: application/json

{
  "name": "Karina",
  "lastName": "capombi",
  "email": "test5@gmail.com",
  "dni": "1125155434",
  "company": "Romar"
}

### delete
delete {{host}}/api/provider/81baed53-e44e-406f-b192-8aa61fb02c2c
token: bearer {{token}}

# end provider

# phone

### create
post {{host}}/api/phone
token: bearer {{token}}
Content-Type: application/json

{
  "userId": "6c34b8d5-c7f2-4bfb-8a38-72205dc31c0c",
  "phones": [
    {
      "type": "celular",
      "value": "123456"
    }
  ]
}

### update
put {{host}}/api/phone/381cb7b1-54a4-4ba5-999f-42bd1c5f1c53
token: bearer {{token}}
Content-Type: application/json

{
  "type": "celular",
  "value": "123456",
  "description": "es un telefono"
}

#end phone

# categories

### create
post {{host}}/api/category
token: bearer {{token}}
Content-Type: application/json

{
  "name": "Bebidas",
  "description": "es una descriptcion"
}

### get
get {{host}}/api/category
token: bearer {{token}}
Content-Type: application/json

### get by id
get {{host}}/api/category/62ee1daf-b44f-4ba3-af9a-57c7d1264518
token: bearer {{token}}
Content-Type: application/json

### update
put {{host}}/api/category/62ee1daf-b44f-4ba3-af9a-57c7d1264518
token: bearer {{token}}
Content-Type: application/json

{
  "name": "Calzado",
  "description": "es una descriptcion de calzado"
}

### set category by id to items
post {{host}}/api/category/items?id=62ee1daf-b44f-4ba3-af9a-57c7d1264518
token: bearer {{token}}
Content-Type: application/json

{
  "items" : ["aed5e249-aaeb-4cf3-ab2e-e463ba8ab370"]
}

#end category

# start sales
### create
post {{host}}/api/sales
token: bearer {{token}}
Content-Type: application/json

{
  "dni": "12344432",
  "date": "2022-09-09",
  "details": [
    {
      "id": "cc196daa-306f-11ed-a261-0242ac120002",
      "amount": 2,
      "pvp": 1
    },
    {
      "id": "169ee313-384a-4584-ba65-251f4e534ed9",
      "amount": 1,
      "pvp": 1
    },
    {
      "id": "ce2d68d2-a431-4a37-a3c7-6d4805dc862b",
      "amount": 1,
      "pvp": 1
    },
        {
      "id": "d57b8a9c-8cb8-423d-b4a5-a6befea90b4b",
      "amount": 1,
      "pvp": 1
    },
    {
      "id": "7d096b98-3d0f-4aea-ab45-293cefee6dfb",
      "amount": 1,
      "pvp": 1
    },
    {
      "id": "31236f9e-df7d-4aa4-a462-4fa96f026908",
      "amount": 1,
      "pvp": 1
    }
  ]
}

### get All
get {{host}}/api/sales
token: bearer {{token}}
Content-Type: application/json

